          name: Build APK
on:
  workflow_dispatch:
jobs:
  build:
run-on: ubuntu-最新
    steps:
      - uses: actions/checkout@v4
      - uses: 操作/设置-java@v4
        with:
          distribution: zulu
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.27.4'
          cache: true
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c
          link-to-system: true
      - run: echo "ANDROID_NDK_HOME=${{steps.setup-ndk.outputs.ndk-path}}" >> $GITHUB_ENV
      - run: sudo apt-get update && sudo apt-get install -y cmake ninja-build
      - run: yes | flutter doctor --android-licenses || true
      - run: flutter酒吧
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: build/app/outputs/flutter-apk/*.apk
